ARG IRSJPY_SERVER_PORT=3001
ARG IRSJPY_DATABASE_URL
FROM node:13.10.1 as build-stage
WORKDIR /app
COPY package*.json /app/
RUN npm install
COPY ./ /app/
RUN npm install
EXPOSE $IRSJPY_SERVER_PORT
ENV IRSJPY_SERVER_PORT $IRSJPY_SERVER_PORT
CMD [ "npm", "start" ]
